=== thierrycoopman/open-banking-tracker-data/schema.json
{
  "title": "Provider",
  "type": "object",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "",
  "required": [
    "id",
    "type",
    "name",
    "iconUrl",
    "verified",
    "website",
    "ipoStatus",
    "countryHQ",
    "countries",
    "webApplication",
    "mobileApps",
    "compliance",
    "sandbox",
    "developerPortalUrl",
    "apiStandards",
    "apiProducts",
    "ownership",
    "stateOwned",
    "stockSymbol",
    "investorRelationsUrl"
  ],
  "additionalProperties": false,
  "properties": { 
    "id": { 
      "type": "string", 
      "pattern": "[a-z0-9-]*$",
      "description": "Unique indentifier",
      "examples": ["abn-amro"]
    },
    "type": { 
      "type": "array",
      "items": {
        "enum": [
          "account",
          "third-party"
        ]
      },
      "description": "Provider type(s)",
      "examples": ["account"]
    },
    "bankType": { 
      "type": "array",
      "description": "Bank type",
      "examples": ["universal"],
      "items": {
        "enum": [
          "universal",
          "retail",
          "corperate",
          "challenger",
          "holding",
          "privatebank"
        ]
      }
    },
    "name": {
      "type": "string",
      "description": "Name of the provider",
      "examples": ["ABN Amro"]
    },
    "legalName": {
      "type": "string",
      "description": "ABN AMRO Group N.V.",
      "examples": ["ABN Amro"]
    },
    "verified": {
      "type": "boolean",
      "description": "Verified by company representative",
      "examples": [true]
    },
    "iconUrl": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https?|http?)://",
      "description": "URL to the icon of the provider (recommended size 400x400)",
      "examples": ["https://res.cloudinary.com/banq/image/upload/v1552240551/radar/icons/abn-amro.jpg"]
    },
    "website": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https?|http?)://",
      "description": "Website of the cloud service",
      "examples": ["https://www.abnamro.com/"]
    },
    "countryHQ": {
      "type": "string",
      "description": "Country (ISO ALPHA-2 code) of HQ",
      "examples": ["NL"]
    },
    "countries": {
      "type": "array",
      "description": "In what countries is the provider active",
      "examples": ["NL", "BE"],
      "uniqueItems": true
    },
    "webApplication": {
      "type": "boolean",
      "description": "Does this provider have a desktop application?",
      "examples": [true]
    },
    "mobileApps": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "operatingSystem": {
            "enum": [
              "ios",
              "android"
            ],
            "examples": ["ios"]
          },
          "storeUrl": {
            "type": "string",
            "examples": ["https://itunes.apple.com/be/app/easy-banking-for-smartphone/id516502006"]
          }
        }
      }
    },
    "compliance": {
      "description": "Applicable regulations and compliance status",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "regulation"
        ],
        "properties": {
          "regulation": { 
            "enum": [
              "PSD2",
              "OB",
              "GDPR"
            ]
          },
          "status": { 
            "enum": [ 
              "inProgress", 
              "ready", 
              "nonCompliant", 
              "unknown" 
            ]
          },
          "sourceUrl": {
            "type": "string",
            "format": "uri",
            "pattern": "^(https?|http?)://"
          }
        }
      }
    },
    "sandbox": {
      "type": "object",
      "properties": {
        "status": {
          "enum": [
            "available",
            "unavailable"
          ]
        },
        "sourceUrl": {
          "anyOf": [
            {
              "type": "string",
              "format": "uri",
              "pattern": "^(https?|http?)://"
            },
            { 
              "type": "null"
            }
          ]
        }
      }
    },
    "developerPortalUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.abnamro.com/"]
        },
        {
          "type": "null"
        }
      ]
    },
    "apiAggregators": {
      "anyOf": [
        {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "enum": [
              "klarna",
              "token",
              "tink",
              "ibanity",
              "figo",
              "bud",
              "truelayer",
              "salt-edge",
              "nordic-api-gateway",
              "yolt",
              "plaid",
              "yapily"
            ]
          }
      },
      {
        "type": "null"
      }]
    },
    "openBankProjectUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.abnamro.com/"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "developerCommunityUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.starlingbank.com/community"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "slackCommunity": {
      "type": "boolean",
      "examples": [true]
    },
    "apiAuth": {
      "type": "array",
      "items": {
        "enum": [
          "OAUTH2",
          "OPENID-CONNECT",
          "UNKNOWN"
        ]
      },
      "examples": ["OAUTH2"]
    },
    "apiReferenceUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.abnamro.com/"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "apiStandards": {
      "description": "The supported standards",
      "type": "array",
      "items": {
        "enum": [
          "OBIE",
          "STET",
          "BERLIN"
        ]
      }
    },
    "apiAccess": {
      "description": "Is the API access limited to verified TPPs only",
      "anyOf": [
        {
          "enum": [
            "verifiedTpp"
          ]
        }, 
        {"type": "null"}
      ]
    },
    "apiProducts": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "label",
          "type",
          "categories",
          "description",
          "documentationUrl",
          "apiReferenceUrl",
          "premium",
          "stage"
        ],
        "properties": {
          "label": {
            "type": "string",
            "examples": ["Account information"]
          }, 
          "type": {
            "enum": [
              "accountInformation",
              "paymentInitiation",
              "paymentRequest",
              "fundsConfirmation",
              "atmLocator",
              "branchLocator",
              "productFinder",
              "cards",
              "consent",
              "auth",
              "fx",
              "other"
            ]
          },
          "specification": {
            "enum": [
              "OBIE-AISP",
              "OBIE-CBPII",
              "OBIE-PISP",
              "STET-AISP",
              "STET-CBPII",
              "STET-PISP",
              "BERLIN1.1",
              "BERLIN1.3"
            ]
          },
          "categories": {
            "type": "array",
            "items": {
              "enum": [
                "accounts",
                "payments",
                "funds",
                "cards",
                "loans",
                "locators",
                "products",
                "fx",
                "auth"
              ]
            }
          },
          "description": {
            "anyOf": [
              {
                "type": "string",
                "description": "Description of the API product",
                "examples": ["Initiate a single payment and retrieve information on the status of the transaction."]
              }, 
              {"type": "null"}
            ]
          },
          "documentationUrl": {
            "anyOf": [
              {
                "type": "string",
                "format": "uri",
                "pattern": "^(https?|http?)://",
                "description": "Aplication url of the provider",
                "examples": ["https://developer.abnamro.com/content/payment-initiation"]
              },
              {
                "type": "null"
              }
            ]
          },
          "apiReferenceUrl": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ],
            "examples": ["https://developer.abnamro.com/api/payment-initiation-v1/payment-initiation-documentation"]
          },
          "premium": {
            "type": "boolean",
            "description": "Is this a premium/paid API?"
          },
          "stage": {
            "enum": [
              "live",
              "sandbox",
              "privateBeta",
              "upcoming",
              "prototype",
              "idea",
              "unknown",
              "deprecated"
            ]
          },
          "customerTypes": {
            "type": "array",
            "items": {
              "enum": [
                "retail",
                "business",
                "corporate",
                "private"
              ]
            }
          },
          "countries": {
            "type": "array",
            "description": "In what countries is the API available",
            "examples": ["NL", "BE"],
            "uniqueItems": true
          },
          "rateLimits": {
            "type": "array",
            "description": "Rate limits that apply to this API",
            "items": {
              "type": "object",
              "properties": {
                "plan": {
                  "type": "string",
                  "examples": ["Default"]
                },
                "limit": {
                  "type": "string",
                  "examples": ["10 per second"]
                }
              }
            }
          }
        }
      }
    },
    "twitter": {
      "anyOf": [
        {
          "type": "string",
          "description": "Twitter handle",
          "examples": ["ABNAMRO"]
        },
        {
          "type": "null"
        }
      ]
    },
    "github": {
      "anyOf": [
        {
          "type": "string",
          "description": "Github organisation id",
          "examples": ["ABNAMRO"]
        },
        {
          "type": "null"
        }
      ]
    },
    "crunchbase": {
      "anyOf": [
        {
          "type": "string",
          "description": "Crunchbase organisation id",
          "examples": ["abn-amro-bank"]
        },
        {
          "type": "null"
        }
      ]
    },
    "fca": {
      "anyOf": [
        {
          "type": "string",
          "description": "FCA firm id",
          "examples": ["001b000000MfnaPAAR"]
        },
        {
          "type": "null"
        }
      ]
    },
    "ipoStatus": {
      "enum": [
        "public",
        "private",
        "subsidiary"
      ],
      "examples": ["public"]
    },
    "stockSymbol": {
      "anyOf": [
        {
          "type": "string",
          "description": "Stock market and ticker symbol",
          "examples": ["AMS:ABN"]
        },
        { 
          "type": "null"
        }
      ]
    },
    "investorRelationsUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://www.abnamro.com/en/investor-relations/index.html"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "financialReports": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "label",
          "date",
          "url"
        ],
        "properties": {
          "label": {
            "type": "string"
          },
          "date": {
            "anyOf": [
              { "type": "string" },
              { "type": "null" }
            ]
          },
          "type": {
            "anyOf": [
              { "type": "null" },
              { 
                "type": "array",
                "items": {
                  "enum": [
                    "analystPresentation",
                    "annualReport",
                    "quarterlyReport",
                    "quarterlyInvestorPresentation",
                    "quarterlyPressRelease",
                    "annualPressRelease"
                  ]
                }
              }
            ]
          },
          "url": {
            "type": "string"
          }
        }
      }
    },
    "ownership": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "shareholderName",
          "shareholderIconUrl",
          "providerId",
          "percentage"
        ],
        "properties": {
          "shareholderName": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ]
          },
          "shareholderIconUrl": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ]
          },
          "providerId": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ],
            "description": "Use the id if this shareholder part of the radar directory"
          },
          "percentage": {
            "anyOf": [
              { 
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "multiplpeOf": 0.01
              },
              { "type": "null" }
            ]
          },
          "sourceUrl": {
            "type": "string",
            "format": "uri",
            "pattern": "^(https?|http?)://"
          }
        }
      }
    },
    "stateOwned": {
      "type": "boolean",
      "description": "Is this is a state-owned provider?",
      "examples": [true]
    },
    "dataBreaches": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "date",
          "url"
        ],
        "properties": {
          "date": { "type": "string" },
          "url": { "type": "string" }
        }
      }
    },
    "articles": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "url"
        ],
        "properties": {
          "date": { "type": "string" },
          "url": { "type": "string" }
        }
      }
    }
  }
}

=== thierrycoopman/open-banking-tracker-data/data/credit-agricole.json
{
  "id": "credit-agricole",
  "type": ["account"],
  "bankType": ["universal"],
  "name": "Crédit Agricole",
  "legalName": "Crédit Agricole S.A.",
  "ipoStatus": "public",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/c_thumb,w_200,g_face/v1552296073/radar/icons/Credit_Agricole.jpg",
  "website": "https://www.credit-agricole.com/",
  "ownership": [],
  "stateOwned": false,
  "countryHQ": "FR",
  "countries": ["EU"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "unavailable"
  },
  "developerPortalUrl": null,
  "openBankProjectUrl": null,
  "apiProducts": [],
  "apiStandards": [],
  "apiAggregators": [
    "klarna",
    "salt-edge"
  ],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios",
      "storeUrl": "https://itunes.apple.com/us/app/ma-banque/id376202925?mt=8"
    },
    {
      "operatingSystem": "android",
      "storeUrl": "https://play.google.com/store/apps/details?id=fr.creditagricole.androidapp&hl=en"
    }
  ],
  "stockSymbol": "EPA:ACA",
  "investorRelationsUrl": "https://www.credit-agricole.com/en/finance/finance",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": "2019-02-14",
      "url": "https://res.cloudinary.com/banq/image/upload/v1552300140/Financial%20Data/CASA_2018-Q4_Slides_EN_Vd%C3%A9f.pdf"
    }
  ],
  "twitter": "CreditAgricole",
  "crunchbase": "credit-agricole",
  "github": "",
  "fca": "001b000000MfF2HAAV",
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/bank-of-scotland.json
{
  "id": "bank-of-scotland",
  "type": ["account"],
  "bankType": ["retail","corperate"],
  "name": "Bank of Scotland",
  "legalName": "Bank of Scotland plc",
  "ipoStatus": "private",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552648073/radar/icons/UfYosl_o_400x400.jpg",
  "website": "https://www.bankofscotland.co.uk/",
  "ownership": [
    { 
      "shareholderName": "Lloyds Banking Group",
      "shareholderIconUrl": "https://res.cloudinary.com/banq/image/upload/v1552296073/radar/icons/Lloyds_Banking_Group.jpg",
      "providerId": "lloyds",
      "percentage": 100.0,
      "sourceUrl": "https://www.lloydsbankinggroup.com/Our-Group/our-heritage/our-history/bank-of-scotland/bank-of-scotland/"
    }
  ],
  "stateOwned": false,
  "countryHQ": "GB",
  "countries": ["GB"],
  "compliance": [
    { 
      "regulation": "OB",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "available"
  },
  "developerPortalUrl": "https://developer.bankofscotland.co.uk/opendata-v2.2",
  "apiProducts": [
    {
      "label": "/branches",
      "type": "branchLocator",
      "categories": ["locators"],
      "description": "Gets a list of all Branch objects.",
      "documentationUrl": null,
      "apiReferenceUrl": "https://developer.bankofscotland.co.uk/opendata-v2.2#get-branches-2.2",
      "premium": false,
      "stage": "sandbox"
    },
    {
      "label": "/personal-current-accounts",
      "type": "accountInformation",
      "categories": ["accounts"],
      "description": "Gets a list of all Personal Current Account objects.",
      "documentationUrl": null,
      "apiReferenceUrl": "https://developer.bankofscotland.co.uk/opendata-v2.2#get-personal-current-accounts-2.2",
      "premium": false,
      "stage": "sandbox"
    },
    {
      "label": "/atms",
      "type": "atmLocator",
      "description": "Gets a list of all ATM objects.",
      "categories": ["locators"],
      "documentationUrl": null,
      "apiReferenceUrl": "https://developer.bankofscotland.co.uk/opendata-v2.2#get-atms-2.2",
      "premium": false,
      "stage": "sandbox"
    },
    {
      "label": "/business-current-accounts",
      "type": "accountInformation",
      "categories": ["accounts"],
      "description": "Gets a list of all Branch Current Account objects.",
      "documentationUrl": null,
      "apiReferenceUrl": "https://developer.bankofscotland.co.uk/opendata-v2.2#get-business-current-accounts-2.2",
      "premium": false,
      "stage": "sandbox"
    },
    {
      "label": "/unsecured-sme-loans",
      "type": "productFinder",
      "description": "Gets a list of all Unsercured SME Lending objects.",
      "categories": ["loans"],
      "documentationUrl": null,
      "apiReferenceUrl": "https://developer.bankofscotland.co.uk/opendata-v2.2#get-unsecured-sme-loans-2.2",
      "premium": false,
      "stage": "sandbox"
    },
    {
      "label": "/commercial-credit-cards",
      "type": "productFinder",
      "description": "Gets a list of all Commerical Credit Card objects.",
      "categories": ["accounts"],
      "documentationUrl": null,
      "apiReferenceUrl": "https://developer.bankofscotland.co.uk/opendata-v2.2#get-commercial-credit-cards-2.2",
      "premium": false,
      "stage": "sandbox"
    }
  ],
  "apiStandards": [],
  "apiAggregators": [
    "klarna",
    "token",
    "yolt"
  ],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios",
      "storeUrl": "https://itunes.apple.com/gb/app/bank-of-scotland-mobile-bank/id485728109?mt=8"
    },
    {
      "operatingSystem": "android",
      "storeUrl": "https://play.google.com/store/apps/details?id=com.grppl.android.shell.BOS&hl=en"
    }
  ],
  "stockSymbol": "LON:LLOY",
  "investorRelationsUrl": "https://www.lloydsbankinggroup.com/investors/",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": "2019-02-20",
      "url": "https://www.lloydsbankinggroup.com/globalassets/documents/investors/2018/2018_lbg_fy_results.pdf"
    }
  ],
  "twitter": "AskBankOfScot",
  "crunchbase": "bank-of-scotland-community-banks",
  "github": null,
  "fca": "001b000000MfGrKAAV",
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/cynergy-bank.json
{
  "id": "cynergy-bank",
  "type": ["account"],
  "bankType": ["retail"],
  "name": "Cynergy Bank",
  "legalName": "Cynergy Bank Ltd",
  "ipoStatus": "private",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552648690/radar/icons/clearbank.jpg",
  "website": "https://www.cynergybank.co.uk/international",
  "ownership": [],
  "stateOwned": false,
  "countryHQ": "GB",
  "countries": ["GB"],
  "compliance": [
    { 
      "regulation": "OB",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "unavailable",
    "sourceUrl": null
  },
  "developerPortalUrl": null,
  "apiProducts": [],
  "apiStandards": [],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios"
    },
    {
      "operatingSystem": "android"
    }
  ],
  "stockSymbol": null,
  "investorRelationsUrl": null,
  "financialReports": [],
  "twitter": "CynergyBank",
  "crunchbase": null,
  "github": null,
  "fca": "001b000000NMgJnAAL",
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/banco-bpm.json
{
  "id": "banco-bpm",
  "type": ["account"],
  "bankType": ["universal"],
  "name": "Banco BPM",
  "legalName": "Banco BPM S.p.A.",
  "ipoStatus": "public",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552296070/radar/icons/Banco_BPM.jpg",
  "website": "https://www.bancobpm.it/index.php",
  "ownership": [],
  "stateOwned": false,
  "countryHQ": "IT",
  "countries": ["IT"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "unavailable"
  },
  "developerPortalUrl": null,
  "apiProducts": [],
  "apiStandards": [],
  "apiAggregators": [
    "klarna"
  ],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios",
      "storeUrl": "https://itunes.apple.com/it/app/youapp/id739705959?mt=8"
    },
    {
      "operatingSystem": "android",
      "storeUrl": "https://play.google.com/store/apps/details?id=com.lynxspa.bancopopolare"
    }
  ],
  "stockSymbol": "BIT: BAMI",
  "investorRelationsUrl": "https://www.bancobpm.it/investor-relations/?lang=en",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": "2019-02-06",
      "url": "https://res.cloudinary.com/banq/image/upload/v1552472376/Financial%20Data/Banco-BPM-FY-2018-Group-Results-presentation-FINAL-1.pdf"
    }
  ],
  "twitter": "BancoBPMSpa",
  "crunchbase": "banco-bpm",
  "github": null,
  "fca": null,
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/swedbank.json
{
  "id": "swedbank",
  "type": ["account"],
  "bankType": ["universal"],
  "name": "Swedbank",
  "legalName": "Swedbank AB",
  "ipoStatus": "public",
  "verified": true,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552296089/radar/icons/Swedbank.jpg",
  "website": "https://www.swedbank.com/",
  "ownership": [],
  "stateOwned": false,
  "countryHQ": "SE",
  "countries": ["SE","EE","LV","LT"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "available",
    "sourceUrl": null
  },
  "developerPortalUrl": "https://developer.swedbank.com/admin/app/home",
  "openBankProjectUrl": "https://www.swedbank.com/openbanking.html",
  "apiProducts": [
    {
      "label": "accounts",
      "type": "accountInformation",
      "categories": ["accounts"],
      "description": null,
      "documentationUrl": "https://developer.swedbank.com/admin/app/api-catalog",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "sandbox"
    },
    {
      "label": "payments",
      "type": "paymentInitiation",
      "categories": ["payments"],
      "description": null,
      "documentationUrl": "https://developer.swedbank.com/admin/app/api-catalog",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "sandbox"
    },
    {
      "label": "invalidateToken",
      "type": "auth",
      "categories": ["auth"],
      "description": null,
      "documentationUrl": "https://developer.swedbank.com/admin/app/api-catalog",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "sandbox"
    },
    {
      "label": "consents",
      "type": "consent",
      "categories": ["accounts"],
      "description": null,
      "documentationUrl": "https://developer.swedbank.com/admin/app/api-catalog",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "sandbox"
    },
    {
      "label": "funds-confirmation",
      "type": "fundsConfirmation",
      "categories": ["funds"],
      "description": null,
      "documentationUrl": "https://developer.swedbank.com/admin/app/api-catalog",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "sandbox"
    }
  ],
  "apiStandards": [],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios"
    },
    {
      "operatingSystem": "android"
    }
  ],
  "stockSymbol": "Stockholm:SWEDA",
  "investorRelationsUrl": "https://www.swedbank.com/investor-relations.html",
  "financialReports": [],
  "twitter": "swedbank",
  "crunchbase": "swedbank",
  "github": null,
  "fca": "001b000000MfF4XAAV",
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/clearbank.json
{
  "id": "clearbank",
  "type": ["account"],
  "bankType": ["retail"],
  "name": "ClearBank",
  "legalName": "Clearbank Ltd.",
  "ipoStatus": "private",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552648690/radar/icons/clearbank.jpg",
  "website": "https://www.clear.bank/",
  "ownership": [],
  "stateOwned": false,
  "countryHQ": "GB",
  "countries": ["GB"],
  "compliance": [
    { 
      "regulation": "OB",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "available",
    "sourceUrl": null
  },
  "developerPortalUrl": "https://www.clear.bank/services/clearbank-api",
  "apiProducts": [],
  "apiStandards": [],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios"
    },
    {
      "operatingSystem": "android"
    }
  ],
  "stockSymbol": null,
  "investorRelationsUrl": null,
  "financialReports": [],
  "twitter": "clear_bank",
  "crunchbase": "clearbank",
  "github": null,
  "fca": "001b000003TEU71AAH",
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/pko-bank-polski.json
{
  "id": "pko-bank-polski",
  "type": ["account"],
  "bankType": ["retail","corperate"],
  "name": "PKO",
  "legalName": "Powszechna Kasa Oszczędności Bank Polski Spółka Akcyjna",
  "ipoStatus": "public",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552296085/radar/icons/PKO_Bank_Polski.png",
  "website": "https://www.pkobp.pl/",
  "ownership": [
    { 
      "shareholderName": "Polish State Treasury",
      "shareholderIconUrl": "https://res.cloudinary.com/banq/image/upload/v1552487385/radar/icons/Polish_Treasury.png",
      "providerId": "Polish State Treasury",
      "percentage": 29.4
    }
  ],
  "stateOwned": true,
  "countryHQ": "PL",
  "countries": ["PL"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "unavailable",
    "sourceUrl": null
  },
  "developerPortalUrl": null,
  "apiProducts": [],
  "apiStandards": [],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios"
    },
    {
      "operatingSystem": "android"
    }
  ],
  "stockSymbol": "WSE:PKO",
  "investorRelationsUrl": "https://www.pkobp.pl/pkobppl-en/investor-relations/",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": null,
      "url": "https://www.pkobp.pl/media_files/ec332d2c-a2ec-4261-a3be-97da284d2393.pdf"
    }
  ],
  "twitter": "PKOBP",
  "crunchbase": "pko-bp",
  "github": null,
  "fca": null,
  "articles": []
}
