=== thierrycoopman/open-banking-tracker-data/schema.json
{
  "title": "Provider",
  "type": "object",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "",
  "required": [
    "id",
    "type",
    "name",
    "iconUrl",
    "verified",
    "website",
    "ipoStatus",
    "countryHQ",
    "countries",
    "webApplication",
    "mobileApps",
    "compliance",
    "sandbox",
    "developerPortalUrl",
    "apiStandards",
    "apiProducts",
    "ownership",
    "stateOwned",
    "stockSymbol",
    "investorRelationsUrl"
  ],
  "additionalProperties": false,
  "properties": { 
    "id": { 
      "type": "string", 
      "pattern": "[a-z0-9-]*$",
      "description": "Unique indentifier",
      "examples": ["abn-amro"]
    },
    "type": { 
      "type": "array",
      "items": {
        "enum": [
          "account",
          "third-party"
        ]
      },
      "description": "Provider type(s)",
      "examples": ["account"]
    },
    "bankType": { 
      "type": "array",
      "description": "Bank type",
      "examples": ["universal"],
      "items": {
        "enum": [
          "universal",
          "retail",
          "corperate",
          "challenger",
          "holding",
          "privatebank"
        ]
      }
    },
    "name": {
      "type": "string",
      "description": "Name of the provider",
      "examples": ["ABN Amro"]
    },
    "legalName": {
      "type": "string",
      "description": "ABN AMRO Group N.V.",
      "examples": ["ABN Amro"]
    },
    "verified": {
      "type": "boolean",
      "description": "Verified by company representative",
      "examples": [true]
    },
    "iconUrl": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https?|http?)://",
      "description": "URL to the icon of the provider (recommended size 400x400)",
      "examples": ["https://res.cloudinary.com/banq/image/upload/v1552240551/radar/icons/abn-amro.jpg"]
    },
    "website": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https?|http?)://",
      "description": "Website of the cloud service",
      "examples": ["https://www.abnamro.com/"]
    },
    "countryHQ": {
      "type": "string",
      "description": "Country (ISO ALPHA-2 code) of HQ",
      "examples": ["NL"]
    },
    "countries": {
      "type": "array",
      "description": "In what countries is the provider active",
      "examples": ["NL", "BE"],
      "uniqueItems": true
    },
    "webApplication": {
      "type": "boolean",
      "description": "Does this provider have a desktop application?",
      "examples": [true]
    },
    "mobileApps": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "operatingSystem": {
            "enum": [
              "ios",
              "android"
            ],
            "examples": ["ios"]
          },
          "storeUrl": {
            "type": "string",
            "examples": ["https://itunes.apple.com/be/app/easy-banking-for-smartphone/id516502006"]
          }
        }
      }
    },
    "compliance": {
      "description": "Applicable regulations and compliance status",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "regulation"
        ],
        "properties": {
          "regulation": { 
            "enum": [
              "PSD2",
              "OB",
              "GDPR"
            ]
          },
          "status": { 
            "enum": [ 
              "inProgress", 
              "ready", 
              "nonCompliant", 
              "unknown" 
            ]
          },
          "sourceUrl": {
            "type": "string",
            "format": "uri",
            "pattern": "^(https?|http?)://"
          }
        }
      }
    },
    "sandbox": {
      "type": "object",
      "properties": {
        "status": {
          "enum": [
            "available",
            "unavailable"
          ]
        },
        "sourceUrl": {
          "anyOf": [
            {
              "type": "string",
              "format": "uri",
              "pattern": "^(https?|http?)://"
            },
            { 
              "type": "null"
            }
          ]
        }
      }
    },
    "developerPortalUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.abnamro.com/"]
        },
        {
          "type": "null"
        }
      ]
    },
    "apiAggregators": {
      "anyOf": [
        {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "enum": [
              "klarna",
              "token",
              "tink",
              "ibanity",
              "figo",
              "bud",
              "truelayer",
              "salt-edge",
              "nordic-api-gateway",
              "yolt",
              "plaid",
              "yapily"
            ]
          }
      },
      {
        "type": "null"
      }]
    },
    "openBankProjectUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.abnamro.com/"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "developerCommunityUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.starlingbank.com/community"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "slackCommunity": {
      "type": "boolean",
      "examples": [true]
    },
    "apiAuth": {
      "type": "array",
      "items": {
        "enum": [
          "OAUTH2",
          "OPENID-CONNECT",
          "UNKNOWN"
        ]
      },
      "examples": ["OAUTH2"]
    },
    "apiReferenceUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.abnamro.com/"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "apiStandards": {
      "description": "The supported standards",
      "type": "array",
      "items": {
        "enum": [
          "OBIE",
          "STET",
          "BERLIN"
        ]
      }
    },
    "apiAccess": {
      "description": "Is the API access limited to verified TPPs only",
      "anyOf": [
        {
          "enum": [
            "verifiedTpp"
          ]
        }, 
        {"type": "null"}
      ]
    },
    "apiProducts": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "label",
          "type",
          "categories",
          "description",
          "documentationUrl",
          "apiReferenceUrl",
          "premium",
          "stage"
        ],
        "properties": {
          "label": {
            "type": "string",
            "examples": ["Account information"]
          }, 
          "type": {
            "enum": [
              "accountInformation",
              "paymentInitiation",
              "paymentRequest",
              "fundsConfirmation",
              "atmLocator",
              "branchLocator",
              "productFinder",
              "cards",
              "consent",
              "auth",
              "fx",
              "other"
            ]
          },
          "specification": {
            "enum": [
              "OBIE-AISP",
              "OBIE-CBPII",
              "OBIE-PISP",
              "STET-AISP",
              "STET-CBPII",
              "STET-PISP",
              "BERLIN1.1",
              "BERLIN1.3"
            ]
          },
          "categories": {
            "type": "array",
            "items": {
              "enum": [
                "accounts",
                "payments",
                "funds",
                "cards",
                "loans",
                "locators",
                "products",
                "fx",
                "auth"
              ]
            }
          },
          "description": {
            "anyOf": [
              {
                "type": "string",
                "description": "Description of the API product",
                "examples": ["Initiate a single payment and retrieve information on the status of the transaction."]
              }, 
              {"type": "null"}
            ]
          },
          "documentationUrl": {
            "anyOf": [
              {
                "type": "string",
                "format": "uri",
                "pattern": "^(https?|http?)://",
                "description": "Aplication url of the provider",
                "examples": ["https://developer.abnamro.com/content/payment-initiation"]
              },
              {
                "type": "null"
              }
            ]
          },
          "apiReferenceUrl": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ],
            "examples": ["https://developer.abnamro.com/api/payment-initiation-v1/payment-initiation-documentation"]
          },
          "premium": {
            "type": "boolean",
            "description": "Is this a premium/paid API?"
          },
          "stage": {
            "enum": [
              "live",
              "sandbox",
              "privateBeta",
              "upcoming",
              "prototype",
              "idea",
              "unknown",
              "deprecated"
            ]
          },
          "customerTypes": {
            "type": "array",
            "items": {
              "enum": [
                "retail",
                "business",
                "corporate",
                "private"
              ]
            }
          },
          "countries": {
            "type": "array",
            "description": "In what countries is the API available",
            "examples": ["NL", "BE"],
            "uniqueItems": true
          },
          "rateLimits": {
            "type": "array",
            "description": "Rate limits that apply to this API",
            "items": {
              "type": "object",
              "properties": {
                "plan": {
                  "type": "string",
                  "examples": ["Default"]
                },
                "limit": {
                  "type": "string",
                  "examples": ["10 per second"]
                }
              }
            }
          }
        }
      }
    },
    "twitter": {
      "anyOf": [
        {
          "type": "string",
          "description": "Twitter handle",
          "examples": ["ABNAMRO"]
        },
        {
          "type": "null"
        }
      ]
    },
    "github": {
      "anyOf": [
        {
          "type": "string",
          "description": "Github organisation id",
          "examples": ["ABNAMRO"]
        },
        {
          "type": "null"
        }
      ]
    },
    "crunchbase": {
      "anyOf": [
        {
          "type": "string",
          "description": "Crunchbase organisation id",
          "examples": ["abn-amro-bank"]
        },
        {
          "type": "null"
        }
      ]
    },
    "fca": {
      "anyOf": [
        {
          "type": "string",
          "description": "FCA firm id",
          "examples": ["001b000000MfnaPAAR"]
        },
        {
          "type": "null"
        }
      ]
    },
    "ipoStatus": {
      "enum": [
        "public",
        "private",
        "subsidiary"
      ],
      "examples": ["public"]
    },
    "stockSymbol": {
      "anyOf": [
        {
          "type": "string",
          "description": "Stock market and ticker symbol",
          "examples": ["AMS:ABN"]
        },
        { 
          "type": "null"
        }
      ]
    },
    "investorRelationsUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://www.abnamro.com/en/investor-relations/index.html"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "financialReports": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "label",
          "date",
          "url"
        ],
        "properties": {
          "label": {
            "type": "string"
          },
          "date": {
            "anyOf": [
              { "type": "string" },
              { "type": "null" }
            ]
          },
          "type": {
            "anyOf": [
              { "type": "null" },
              { 
                "type": "array",
                "items": {
                  "enum": [
                    "analystPresentation",
                    "annualReport",
                    "quarterlyReport",
                    "quarterlyInvestorPresentation",
                    "quarterlyPressRelease",
                    "annualPressRelease"
                  ]
                }
              }
            ]
          },
          "url": {
            "type": "string"
          }
        }
      }
    },
    "ownership": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "shareholderName",
          "shareholderIconUrl",
          "providerId",
          "percentage"
        ],
        "properties": {
          "shareholderName": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ]
          },
          "shareholderIconUrl": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ]
          },
          "providerId": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ],
            "description": "Use the id if this shareholder part of the radar directory"
          },
          "percentage": {
            "anyOf": [
              { 
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "multiplpeOf": 0.01
              },
              { "type": "null" }
            ]
          },
          "sourceUrl": {
            "type": "string",
            "format": "uri",
            "pattern": "^(https?|http?)://"
          }
        }
      }
    },
    "stateOwned": {
      "type": "boolean",
      "description": "Is this is a state-owned provider?",
      "examples": [true]
    },
    "dataBreaches": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "date",
          "url"
        ],
        "properties": {
          "date": { "type": "string" },
          "url": { "type": "string" }
        }
      }
    },
    "articles": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "url"
        ],
        "properties": {
          "date": { "type": "string" },
          "url": { "type": "string" }
        }
      }
    }
  }
}

=== thierrycoopman/open-banking-tracker-data/data/OakNorth.json
{
  "id": "OakNorth",
  "type": ["account"],
  "bankType": ["challenger"],
  "name": "OakNorth Bank",
  "legalName": "OakNorth Bank plc",
  "ipoStatus": "private",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1553597743/radar/icons/OakNorth.jpg",
  "website": "https://www.oaknorth.com/",
  "ownership": [],
  "stateOwned": false,
  "countryHQ": "GB",
  "countries": ["GB"],
  "compliance": [
    { 
      "regulation": "OB",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "unavailable"
  },
  "developerPortalUrl": null,
  "apiProducts": [],
  "apiStandards": [],
  "webApplication": true,
  "mobileApps": [],
  "stockSymbol": null,
  "investorRelationsUrl": null,
  "financialReports": [
    {
      "label": "2018",
      "date": null,
      "url": "https://www.oaknorth.com/wp-content/uploads/2019/03/Annual-accounts-2018-OakNorth-1.pdf",
      "documentType": "annualreport"
    }
  ],
  "twitter": "oaknorth",
  "crunchbase": "oaknorth-bank",
  "github": null,
  "fca": "001b000000aQtn8AAC",
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/bankinter.json
{
  "id": "bankinter",
  "type": ["account"],
  "bankType": ["universal"],
  "name": "Bankinter",
  "legalName": "Bankinter Gestion de Activos SA",
  "ipoStatus": "public",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552296072/radar/icons/Bankinter.png",
  "website": "https://www.bankinter.pt/",
  "ownership": [
    { 
      "shareholderName": "Cartival S.A.",
      "shareholderIconUrl": "https://res.cloudinary.com/banq/image/upload/v1552491769/radar/icons/Cartival.png",
      "providerId": null,
      "percentage": 22.9,
      "sourceUrl": "https://webcorporativa.bankinter.com/stf/web_corporativa/accionistas_e_inversores/info_financiera/memoria/2018/informe_anual_integrado_2018.pdf"
    }
  ],
  "stateOwned": false,
  "countryHQ": "ES",
  "countries": ["ES","PT"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "unavailable",
    "sourceUrl":null
  },
  "developerPortalUrl": null,
  "apiProducts": [],
  "apiStandards": [],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios"
    },
    {
      "operatingSystem": "android"
    }
  ],
  "stockSymbol": "BME:BKT",
  "investorRelationsUrl": "https://webcorporativa.bankinter.com/www2/corporativa/en/inf_financiera_cnmv/informacion_financiera/agenda_inversor",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": "2019-01-24",
      "url": "https://webcorporativa.bankinter.com/stf/traducciones/ingles/web_corporativa/accionistas_e_inversores/info_financiera/resultados/2018/cuarto_trimestre/bankinter_4q18.pdf"
    }
  ],
  "twitter": "bankinter",
  "crunchbase": "bankinter",
  "github": null,
  "fca": "001b000000NMXIGAA5",
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/unicredit.json
{
  "id": "unicredit",
  "type": ["account"],
  "bankType": ["universal"],
  "name": "Unicredit",
  "legalName": "UniCredit S.p.A.",
  "ipoStatus": "public",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552296097/radar/icons/Unicredit.jpg",
  "website": "https://www.unicreditgroup.eu/en.html",
  "ownership": [],
  "stateOwned": false,
  "countryHQ": "IT",
  "countries": ["EU"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "available",
    "sourceUrl": null
  },
  "developerPortalUrl": "https://developer.unicredit.eu/",
  "apiProducts": [],
  "apiStandards": [],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios"
    },
    {
      "operatingSystem": "android"
    }
  ],
  "stockSymbol": "BIT:UCG",
  "investorRelationsUrl": "https://www.unicreditgroup.eu/en/investors/financial-reports.html",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": "2018-11-08",
      "url": "https://www.unicreditgroup.eu/en/press-media/press-releases-price-sensitive/2018/unicredit--a-paneuropean-winner.html"
    }
  ],
  "twitter": "UniCredit_PR",
  "crunchbase": "unicredit",
  "github": "unicredit",
  "fca": "001b000000MfJO8AAN",
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/beobank.json
{
  "id": "beobank",
  "type": ["account"],
  "bankType": ["retail"],
  "name": "Beobank",
  "legalName": "BEOBANK NV/SA",
  "ipoStatus": "private",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1553173196/radar/icons/Beobank.png",
  "website": "https://www.beobank.be/fr/particulier/",
  "ownership": [
    { 
      "shareholderName": "Credit Mutuel",
      "shareholderIconUrl": "https://res.cloudinary.com/banq/image/upload/v1552296073/radar/icons/Credit_Mutuel.jpg",
      "providerId": "credit-mutuel",
      "percentage": 100.0,
      "sourceUrl": "https://www.creditmutuel.fr/cmne/fr/banques/site-institutionnel/publications/rapport-annuel/2017/en/rapport-annuel-2017_en_global-final.pdf"
    }
  ],
  "stateOwned": false,
  "countryHQ": "BE",
  "countries": ["BE","NL","LU"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "available"
  },
  "developerPortalUrl": "https://online.beobank.be/oauth2/en/devportal/",
  "apiProducts": [],
  "apiStandards": [],
  "apiAggregators": [
    "klarna"
  ],
  "apiAccess": null,
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios",
      "storeUrl": "https://itunes.apple.com/be/app/beobank-mobile/id1008666594?mt=8"
    },
    {
      "operatingSystem": "android",
      "storeUrl": "https://play.google.com/store/apps/details?id=com.beobank_prod.bad&hl=en"
    }
  ],
  "stockSymbol": null,
  "investorRelationsUrl": "http://www.bfcm.creditmutuel.fr/en/bfcm/presentation/index.html",
  "financialReports": [
    {
      "label": "H1 2018",
      "date": "2018-08-07",
      "url": "http://www.bfcm.creditmutuel.fr/en/bfcm/pdf/DOCREF_JUNE2018_VENG.pdf"
    }
  ],
  "twitter": "beobank",
  "crunchbase": null,
  "github": null,
  "fca": null,
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/citi.json
{
  "id": "citi",
  "type": ["account"],
  "bankType": ["universal"],
  "name": "Citi",
  "legalName": "Citibank, N. A.",
  "ipoStatus": "public",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552641830/radar/icons/Citi.jpg",
  "website": "https://online.citi.com/US/login.do",
  "ownership": [],
  "stateOwned": false,
  "countryHQ": "US",
  "countries": ["GB","PL","RU"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    },
    { 
      "regulation": "OB",
      "status": "ready"
    }
    ],
  "sandbox": {
    "status": "available",
    "sourceUrl": null
  },
  "developerPortalUrl": "https://sandbox.developerhub.citi.com/api-catalog-list",
  "apiProducts": [
    {
      "label": "Accounts",
      "type": "accountInformation",
      "categories": ["accounts"],
      "description": "Verify Citi customer accounts and grant your apps access to account data.",
      "documentationUrl": "https://sandbox.developerhub.citi.com/api/united-kingdom/accounts/overview",
      "apiReferenceUrl": "https://sandbox.developerhub.citi.com/api/united-kingdom/accounts/documentation",
      "premium": false,
      "stage": "sandbox",
      "countries": ["GB","PL"]
    },
    {
      "label": "Authorize",
      "type": "auth",
      "description": "Verify Citi customer accounts and grant your apps access to account data.",
      "categories": ["auth"],
      "documentationUrl": null,
      "apiReferenceUrl": "https://sandbox.developerhub.citi.com/api/united-kingdom/authorize/documentation",
      "premium": false,
      "stage": "sandbox",
      "countries": ["GB","PL"]
    },
    {
      "label": "Customers",
      "type": "accountInformation",
      "categories": ["accounts"],
      "description": "Get approved access to shared Citi customer profile data for deeper engagement.",
      "documentationUrl": "https://sandbox.developerhub.citi.com/api/united-kingdom/customers/overview",
      "apiReferenceUrl": "https://sandbox.developerhub.citi.com/api/united-kingdom/customers/documentation",
      "premium": false,
      "stage": "sandbox",
      "countries": ["GB","PL"]
    },
    {
      "label": "Money Movement",
      "type": "paymentInitiation",
      "categories": ["payments"],
      "description": "Give Citi customers the ability to move money across accounts and institutions.",
      "documentationUrl": "https://sandbox.developerhub.citi.com/api/united-kingdom/money-movement/overview",
      "apiReferenceUrl": "https://sandbox.developerhub.citi.com/api/united-kingdom/money-movement/documentation",
      "premium": false,
      "stage": "sandbox",
      "countries": ["GB","PL"]
    },
    {
      "label": "Utilities",
      "type": "other",
      "categories": ["products"],
      "description": "Allow developers to get country specific variations.",
      "documentationUrl": null,
      "apiReferenceUrl": "https://sandbox.developerhub.citi.com/api/united-kingdom/utilities/documentation",
      "premium": false,
      "stage": "sandbox",
      "countries": ["GB","PL","RU"]
    },
    {
      "label": "Onboarding",
      "type": "other",
      "categories": ["accounts"],
      "description": "Tap into the power of Citi acquisitions partner services.",
      "documentationUrl": "https://sandbox.developerhub.citi.com/api/poland/onboarding/overview",
      "apiReferenceUrl": "https://sandbox.developerhub.citi.com/api/poland/onboarding/documentation",
      "premium": false,
      "stage": "sandbox",
      "countries": ["PL","RU"] 
    },
    {
      "label": "Pay With Points",
      "type": "paymentInitiation",
      "categories": ["payments"],
      "description": "Enable your app to accept Citi customersâ€™ Citi rewards points to pay for their purchases.",
      "documentationUrl": "https://sandbox.developerhub.citi.com/api/russia/pay-with-points/overview",
      "apiReferenceUrl": "https://sandbox.developerhub.citi.com/api/russia/pay-with-points/documentation",
      "premium": false,
      "stage": "sandbox",
      "countries": ["PL","RU"] 
    }
  ],
  "apiStandards": [],
  "apiAggregators": [
    "klarna"
  ],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios",
      "storeUrl": "https://itunes.apple.com/us/app/citi-mobile/id301724680?mt=8"
    },
    {
      "operatingSystem": "android",
      "storeUrl": "https://play.google.com/store/apps/details?id=com.citi.citimobile&hl=en"
    }
  ],
  "stockSymbol": "NYSE:C",
  "investorRelationsUrl": "https://www.citigroup.com/citi/investor/pres.htm",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": "2019-01-24",
      "url": "https://www.citigroup.com/citi/news/2018/181220a.htm"
    }
  ],
  "twitter": "citi",
  "crunchbase": "citigroup",
  "github": "citi",
  "fca": "001b000000MfF27AAF",
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/natwest.json
{
  "id": "natwest",
  "type": ["account"],
  "bankType": ["retail","corperate"],
  "name": "Natwest",
  "legalName": "National Westminster Bank Plc",
  "ipoStatus": "private",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552296074/radar/icons/Natwest.jpg",
  "website": "https://personal.natwest.com/personal.html",
  "ownership": [
    { 
      "shareholderName": "The Royal Bank of Scotland Group plc",
      "shareholderIconUrl": "https://res.cloudinary.com/banq/image/upload/v1552312195/radar/icons/Royal_Bank_of_Scotland.jpg",
      "providerId": "royal-bank-of-scotland",
      "percentage": 100.0
    }
  ],
  "stateOwned": false,
  "countryHQ": "GB",
  "countries": ["GB"],
  "compliance": [
    { 
      "regulation": "OB",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "available"
  },
  "developerPortalUrl": "https://developer.natwest.com/apiportal",
  "apiProducts": [
    {
      "label": "Account and Transaction API",
      "type": "accountInformation",
      "categories": ["accounts"],
      "description": "The Account and Transaction API is intended to give a third party, upon consent of the owning customer, access to product, service and transaction information relating to that account such that they may provide the customer with value-adding products or services.",
      "documentationUrl": "https://developer.natwest.com/apiportal/api-catalogue",
      "apiReferenceUrl": "https://developer.natwest.com/apiportal/documentation/account-info",
      "premium": false,
      "stage": "sandbox"
    },
    {
      "label": "Payment Initiation API",
      "type": "paymentInitiation",
      "categories": ["payments"],
      "description": "The payment initiation API enables any third party, registered as an approved Payment Initiation Service Provider (PISP) with Open Banking, to provision secure payments on behalf of our customers. The payment, once approved and authorised by the customer, is submitted for processing. We currently support the submission of a single, immediate, domestic payment from our customerâ€™s UK personal and business current accounts.",
      "documentationUrl": "https://developer.natwest.com/apiportal/api-catalogue",
      "apiReferenceUrl": "https://developer.natwest.com/apiportal/documentation/payment-initiation",
      "premium": false,
      "stage": "sandbox"
    }
  ],
  "apiStandards": [],
  "apiAggregators": [
    "token",
    "yolt"
  ],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios"
    },
    {
      "operatingSystem": "android"
    }
  ],
  "stockSymbol": "LON:RBS",
  "investorRelationsUrl": "https://investors.rbs.com/",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": "2019-02-15",
      "url": "https://investors.rbs.com/~/media/Files/R/RBS-IR/results-center/annual-report-2018.pdf"
    }
  ],
  "twitter": "Natwest_help",
  "crunchbase": "natwest-bank1",
  "github": null,
  "fca": "001b000000MfFIWAA3",
  "articles": []
}
