=== thierrycoopman/open-banking-tracker-data/schema.json
{
  "title": "Provider",
  "type": "object",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "",
  "required": [
    "id",
    "type",
    "name",
    "iconUrl",
    "verified",
    "website",
    "ipoStatus",
    "countryHQ",
    "countries",
    "webApplication",
    "mobileApps",
    "compliance",
    "sandbox",
    "developerPortalUrl",
    "apiStandards",
    "apiProducts",
    "ownership",
    "stateOwned",
    "stockSymbol",
    "investorRelationsUrl"
  ],
  "additionalProperties": false,
  "properties": { 
    "id": { 
      "type": "string", 
      "pattern": "[a-z0-9-]*$",
      "description": "Unique indentifier",
      "examples": ["abn-amro"]
    },
    "type": { 
      "type": "array",
      "items": {
        "enum": [
          "account",
          "third-party"
        ]
      },
      "description": "Provider type(s)",
      "examples": ["account"]
    },
    "bankType": { 
      "type": "array",
      "description": "Bank type",
      "examples": ["universal"],
      "items": {
        "enum": [
          "universal",
          "retail",
          "corperate",
          "challenger",
          "holding",
          "privatebank"
        ]
      }
    },
    "name": {
      "type": "string",
      "description": "Name of the provider",
      "examples": ["ABN Amro"]
    },
    "legalName": {
      "type": "string",
      "description": "ABN AMRO Group N.V.",
      "examples": ["ABN Amro"]
    },
    "verified": {
      "type": "boolean",
      "description": "Verified by company representative",
      "examples": [true]
    },
    "iconUrl": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https?|http?)://",
      "description": "URL to the icon of the provider (recommended size 400x400)",
      "examples": ["https://res.cloudinary.com/banq/image/upload/v1552240551/radar/icons/abn-amro.jpg"]
    },
    "website": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https?|http?)://",
      "description": "Website of the cloud service",
      "examples": ["https://www.abnamro.com/"]
    },
    "countryHQ": {
      "type": "string",
      "description": "Country (ISO ALPHA-2 code) of HQ",
      "examples": ["NL"]
    },
    "countries": {
      "type": "array",
      "description": "In what countries is the provider active",
      "examples": ["NL", "BE"],
      "uniqueItems": true
    },
    "webApplication": {
      "type": "boolean",
      "description": "Does this provider have a desktop application?",
      "examples": [true]
    },
    "mobileApps": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "operatingSystem": {
            "enum": [
              "ios",
              "android"
            ],
            "examples": ["ios"]
          },
          "storeUrl": {
            "type": "string",
            "examples": ["https://itunes.apple.com/be/app/easy-banking-for-smartphone/id516502006"]
          }
        }
      }
    },
    "compliance": {
      "description": "Applicable regulations and compliance status",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "regulation"
        ],
        "properties": {
          "regulation": { 
            "enum": [
              "PSD2",
              "OB",
              "GDPR"
            ]
          },
          "status": { 
            "enum": [ 
              "inProgress", 
              "ready", 
              "nonCompliant", 
              "unknown" 
            ]
          },
          "sourceUrl": {
            "type": "string",
            "format": "uri",
            "pattern": "^(https?|http?)://"
          }
        }
      }
    },
    "sandbox": {
      "type": "object",
      "properties": {
        "status": {
          "enum": [
            "available",
            "unavailable"
          ]
        },
        "sourceUrl": {
          "anyOf": [
            {
              "type": "string",
              "format": "uri",
              "pattern": "^(https?|http?)://"
            },
            { 
              "type": "null"
            }
          ]
        }
      }
    },
    "developerPortalUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.abnamro.com/"]
        },
        {
          "type": "null"
        }
      ]
    },
    "apiAggregators": {
      "anyOf": [
        {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "enum": [
              "klarna",
              "token",
              "tink",
              "ibanity",
              "figo",
              "bud",
              "truelayer",
              "salt-edge",
              "nordic-api-gateway",
              "yolt",
              "plaid",
              "yapily"
            ]
          }
      },
      {
        "type": "null"
      }]
    },
    "openBankProjectUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.abnamro.com/"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "developerCommunityUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.starlingbank.com/community"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "slackCommunity": {
      "type": "boolean",
      "examples": [true]
    },
    "apiAuth": {
      "type": "array",
      "items": {
        "enum": [
          "OAUTH2",
          "OPENID-CONNECT",
          "UNKNOWN"
        ]
      },
      "examples": ["OAUTH2"]
    },
    "apiReferenceUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://developer.abnamro.com/"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "apiStandards": {
      "description": "The supported standards",
      "type": "array",
      "items": {
        "enum": [
          "OBIE",
          "STET",
          "BERLIN"
        ]
      }
    },
    "apiAccess": {
      "description": "Is the API access limited to verified TPPs only",
      "anyOf": [
        {
          "enum": [
            "verifiedTpp"
          ]
        }, 
        {"type": "null"}
      ]
    },
    "apiProducts": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "label",
          "type",
          "categories",
          "description",
          "documentationUrl",
          "apiReferenceUrl",
          "premium",
          "stage"
        ],
        "properties": {
          "label": {
            "type": "string",
            "examples": ["Account information"]
          }, 
          "type": {
            "enum": [
              "accountInformation",
              "paymentInitiation",
              "paymentRequest",
              "fundsConfirmation",
              "atmLocator",
              "branchLocator",
              "productFinder",
              "cards",
              "consent",
              "auth",
              "fx",
              "other"
            ]
          },
          "specification": {
            "enum": [
              "OBIE-AISP",
              "OBIE-CBPII",
              "OBIE-PISP",
              "STET-AISP",
              "STET-CBPII",
              "STET-PISP",
              "BERLIN1.1",
              "BERLIN1.3"
            ]
          },
          "categories": {
            "type": "array",
            "items": {
              "enum": [
                "accounts",
                "payments",
                "funds",
                "cards",
                "loans",
                "locators",
                "products",
                "fx",
                "auth"
              ]
            }
          },
          "description": {
            "anyOf": [
              {
                "type": "string",
                "description": "Description of the API product",
                "examples": ["Initiate a single payment and retrieve information on the status of the transaction."]
              }, 
              {"type": "null"}
            ]
          },
          "documentationUrl": {
            "anyOf": [
              {
                "type": "string",
                "format": "uri",
                "pattern": "^(https?|http?)://",
                "description": "Aplication url of the provider",
                "examples": ["https://developer.abnamro.com/content/payment-initiation"]
              },
              {
                "type": "null"
              }
            ]
          },
          "apiReferenceUrl": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ],
            "examples": ["https://developer.abnamro.com/api/payment-initiation-v1/payment-initiation-documentation"]
          },
          "premium": {
            "type": "boolean",
            "description": "Is this a premium/paid API?"
          },
          "stage": {
            "enum": [
              "live",
              "sandbox",
              "privateBeta",
              "upcoming",
              "prototype",
              "idea",
              "unknown",
              "deprecated"
            ]
          },
          "customerTypes": {
            "type": "array",
            "items": {
              "enum": [
                "retail",
                "business",
                "corporate",
                "private"
              ]
            }
          },
          "countries": {
            "type": "array",
            "description": "In what countries is the API available",
            "examples": ["NL", "BE"],
            "uniqueItems": true
          },
          "rateLimits": {
            "type": "array",
            "description": "Rate limits that apply to this API",
            "items": {
              "type": "object",
              "properties": {
                "plan": {
                  "type": "string",
                  "examples": ["Default"]
                },
                "limit": {
                  "type": "string",
                  "examples": ["10 per second"]
                }
              }
            }
          }
        }
      }
    },
    "twitter": {
      "anyOf": [
        {
          "type": "string",
          "description": "Twitter handle",
          "examples": ["ABNAMRO"]
        },
        {
          "type": "null"
        }
      ]
    },
    "github": {
      "anyOf": [
        {
          "type": "string",
          "description": "Github organisation id",
          "examples": ["ABNAMRO"]
        },
        {
          "type": "null"
        }
      ]
    },
    "crunchbase": {
      "anyOf": [
        {
          "type": "string",
          "description": "Crunchbase organisation id",
          "examples": ["abn-amro-bank"]
        },
        {
          "type": "null"
        }
      ]
    },
    "fca": {
      "anyOf": [
        {
          "type": "string",
          "description": "FCA firm id",
          "examples": ["001b000000MfnaPAAR"]
        },
        {
          "type": "null"
        }
      ]
    },
    "ipoStatus": {
      "enum": [
        "public",
        "private",
        "subsidiary"
      ],
      "examples": ["public"]
    },
    "stockSymbol": {
      "anyOf": [
        {
          "type": "string",
          "description": "Stock market and ticker symbol",
          "examples": ["AMS:ABN"]
        },
        { 
          "type": "null"
        }
      ]
    },
    "investorRelationsUrl": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri",
          "pattern": "^(https?|http?)://",
          "description": "Aplication url of the provider",
          "examples": ["https://www.abnamro.com/en/investor-relations/index.html"]
        }, 
        {
          "type": "null"
        }
      ]
    },
    "financialReports": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "label",
          "date",
          "url"
        ],
        "properties": {
          "label": {
            "type": "string"
          },
          "date": {
            "anyOf": [
              { "type": "string" },
              { "type": "null" }
            ]
          },
          "type": {
            "anyOf": [
              { "type": "null" },
              { 
                "type": "array",
                "items": {
                  "enum": [
                    "analystPresentation",
                    "annualReport",
                    "quarterlyReport",
                    "quarterlyInvestorPresentation",
                    "quarterlyPressRelease",
                    "annualPressRelease"
                  ]
                }
              }
            ]
          },
          "url": {
            "type": "string"
          }
        }
      }
    },
    "ownership": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "shareholderName",
          "shareholderIconUrl",
          "providerId",
          "percentage"
        ],
        "properties": {
          "shareholderName": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ]
          },
          "shareholderIconUrl": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ]
          },
          "providerId": {
            "anyOf" : [
              { "type": "string" },
              { "type": "null" }
            ],
            "description": "Use the id if this shareholder part of the radar directory"
          },
          "percentage": {
            "anyOf": [
              { 
                "type": "number",
                "minimum": 0,
                "maximum": 100,
                "multiplpeOf": 0.01
              },
              { "type": "null" }
            ]
          },
          "sourceUrl": {
            "type": "string",
            "format": "uri",
            "pattern": "^(https?|http?)://"
          }
        }
      }
    },
    "stateOwned": {
      "type": "boolean",
      "description": "Is this is a state-owned provider?",
      "examples": [true]
    },
    "dataBreaches": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "date",
          "url"
        ],
        "properties": {
          "date": { "type": "string" },
          "url": { "type": "string" }
        }
      }
    },
    "articles": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "url"
        ],
        "properties": {
          "date": { "type": "string" },
          "url": { "type": "string" }
        }
      }
    }
  }
}

=== thierrycoopman/open-banking-tracker-data/data/bank-of-ireland.json
{
  "id": "bank-of-ireland",
  "type": ["account"],
  "bankType": ["retail","corperate"],
  "name": "Bank of Ireland",
  "legalName": "Bank of Ireland Group plc",
  "ipoStatus": "public",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552296071/radar/icons/Bank_of_Ireland.jpg",
  "website": "https://www.bankofireland.com/",
  "ownership": [
    { 
      "shareholderName": "Irish State",
      "shareholderIconUrl": "https://res.cloudinary.com/banq/image/upload/v1552486084/radar/icons/Irish_State.webp",
      "providerId": "Irish State",
      "percentage": 14.0
    }
  ],
  "stateOwned": true,
  "countryHQ": "IE",
  "countries": ["IE","GB"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    },
    { 
      "regulation": "OB",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "unavailable",
    "sourceUrl": null
  },
  "developerPortalUrl": null,
  "apiProducts": [],
  "apiStandards": [],
  "apiAggregators": [
    "token",
    "yolt"
  ],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios"
    },
    {
      "operatingSystem": "android"
    }
  ],
  "stockSymbol": "LON:BIRG",
  "investorRelationsUrl": "https://investorrelations.bankofireland.com/",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": "2019-02-25",
      "url": "https://investorrelations.bankofireland.com/app/uploads/Bank-of-Ireland-Investor-Presentation-Dec-2018-1.pdf"
    }
  ],
  "twitter": "BankOfIreland",
  "crunchbase": "bank-of-ireland",
  "github": null,
  "fca": "001b000000NMNtpAAH",
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/soc-gen.json
{
  "id": "soc-gen",
  "type": ["account"],
  "bankType": ["universal"],
  "name": "Société Générale",
  "legalName": "Société Générale S.A.",
  "ipoStatus": "public",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552296086/radar/icons/Societe_Generale.jpg",
  "website": "https://www.societegenerale.com/en/home",
  "ownership": [],
  "stateOwned": false,
  "countryHQ": "FR",
  "countries": ["FR","GB","LU","BE"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    },
    { 
      "regulation": "OB",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "unavailable",
    "sourceUrl": null
    },
  "developerPortalUrl": null,
  "apiProducts": [],
  "apiStandards": [],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios",
      "storeUrl": "https://itunes.apple.com/gb/app/lappli-soci%C3%A9t%C3%A9-g%C3%A9n%C3%A9rale/id376991016?mt=8"
    },
    {
      "operatingSystem": "android",
      "storeUrl": "https://play.google.com/store/apps/details?id=mobi.societegenerale.mobile.lappli&hl=en"
    }
  ],
"stockSymbol": "EPA:GLE:EN",
 "investorRelationsUrl": "https://www.societegenerale.com/en/investors",
 "financialReports": [
   {
     "label": "Q4 2018",
     "date": "2019-02-07",
     "documentType": ["annualpressrelease","quarterlypressrelease"],
     "url": "https://www.societegenerale.com/sites/default/files/documents/R%C3%A9sultats%20financiers/2018/Q4/pr_q4_2018.pdf"
   }
 ],
 "twitter": "societegenerale",
 "crunchbase": "societe-generale",
 "github": "societe-generale",
 "fca": "001b000000MfF4FAAV",
 "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/kbc-bank.json
{
  "id": "kbc-bank",
  "type": ["account"],
  "bankType": ["universal"],
  "name": "KBC",
  "legalName": "KBC Group N.V.",
  "ipoStatus": "public",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552296072/radar/icons/KBC.jpg",
  "website": "https://www.kbc.com/en",
  "ownership": [],
  "stateOwned": false,
  "countryHQ": "BE",
  "countries": ["BE","BG","HU","CZ","SK"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "available",
    "sourceUrl": "https://www.kbc.com/system/files/doc/newsroom/pressreleases/2019/20190311_PR_DeveloperPortal_EN.pdf"
  },
  "developerPortalUrl": "https://developer.kbc-group.com/content/developer/kbc-be/en.html",
  "apiAuth": ["OAUTH2"],
  "apiProducts": [
     {
      "label": "Account Information Service (AIS)",
      "type": "accountInformation",
      "categories": ["accounts"],
      "description": "Access current account or credit card information (with your customer's explicit consent).",
      "documentationUrl": "https://developer.kbc-group.com/content/developer/kbc-be/en/apis/ais.html",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "sandbox",
      "specification": "BERLIN1.1"
    },
    {
      "label": "Payment Initiation Services (PIS)",
      "type": "paymentInitiation",
      "categories": ["payments"],
      "description": "Initiate an immediate payment to a SEPA-zone beneficiary (with your customer's explicit consent)",
      "documentationUrl": "https://developer.kbc-group.com/content/developer/kbc-be/en/apis/pis.html",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "sandbox",
      "specification": "BERLIN1.1"
    },
    {
      "label": "Confirmation of Funds (COF)",
      "type": "fundsConfirmation",
      "categories": ["funds"],
      "description": "Check availability of a KBC customer's current account or credit card funds (with their explicit consent).",
      "documentationUrl": "https://developer.kbc-group.com/content/developer/kbc-be/en/apis/cof.html",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "sandbox",
      "specification": "BERLIN1.1"
    },
    {
      "label": "Authorization API",
      "type": "auth",
      "categories": ["auth"],
      "description": "Compose & trigger authorization request. Get & refresh tokens. Security endpoints.",
      "documentationUrl": "https://developer.kbc-group.com/content/developer/kbc-be/en/apis/authorization.html",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "sandbox"
    }
  ],
  "apiStandards": [],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios"
    },
    {
      "operatingSystem": "android"
    }
  ],
  "stockSymbol": "EBR:KBC",
  "investorRelationsUrl": "https://www.kbc.com/en/investor-relations",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": "2019-02-14",
      "url": "https://www.kbc.com/nl/system/files/doc/investor-relations/Results/4Q2018/4Q2018_Quarterly_Report_en.pdf"
    }
  ],
  "twitter": "KBC_Group",
  "crunchbase": "kbc-bank",
  "github": null,
  "fca": "001b000000MfHWzAAN",
  "articles": [
    {
      "url": "https://newsroom.kbc.com/belgians-positive-towards-integrated-banking-app-kbc-mobile-gives-direct-access-to-current-accounts-held-with-other-banks",
      "date": "2018-03-05"
    }
  ]
}

=== thierrycoopman/open-banking-tracker-data/data/caixabank.json
{
  "id": "caixabank",
  "type": ["account"],
  "bankType": ["retail","corperate"],
  "name": "CaixaBank",
  "legalName": "Caixabank, SA.",
  "ipoStatus": "public",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/v1552381252/radar/icons/CaixaBank.jpg",
  "website": "https://www.caixabank.es/particular/home/particulares_es.html",
  "ownership": [
    { 
      "shareholderName": "Criteria Caixa",
      "shareholderIconUrl": "https://res.cloudinary.com/banq/image/upload/v1552381367/radar/icons/CriteriaCaixa.jpg",
      "providerId": null,
      "percentage": 40.0
    }
  ],
  "stateOwned": false,
  "countryHQ": "ES",
  "countries": ["ES","PT"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "unavailable",
    "sourceUrl": null
  },
  "developerPortalUrl": null,
  "apiProducts": [],
  "apiStandards": [],
  "apiAggregators": [
    "klarna"
  ],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios",
      "storeUrl": "https://itunes.apple.com/us/app/caixabank/id318806094?mt=8"
    },
    {
      "operatingSystem": "android",
      "storeUrl": "https://play.google.com/store/apps/details?id=es.lacaixa.mobile.android.newwapicon&hl=en"
    }
  ],
  "stockSymbol": "CABK:SM",
  "investorRelationsUrl": "https://www.caixabank.com/inversoresinstitucionales_en.html",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": "2019-02-01",
      "url": "https://www.caixabank.com/deployedfiles/caixabank/Estaticos/PDFs/Informacion_accionistas_inversores/IPP_4T18_ENG.PDF"
    }
  ],
  "twitter": "caixabank",
  "crunchbase": "caixabank",
  "github": null,
  "fca": "001b000000MfgbgAAB",
  "articles": []
}

=== thierrycoopman/open-banking-tracker-data/data/abn-amro.json
{
  "id": "abn-amro",
  "type": ["account"],
  "bankType": ["universal"],
  "name": "ABN Amro",
  "legalName": "ABN AMRO Group N.V.",
  "ipoStatus": "public",
  "verified": false,
  "iconUrl": "https://res.cloudinary.com/banq/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1552240551/radar/icons/abn-amro.jpg",
  "website": "https://www.abnamro.com/",
  "ownership": [
    { 
      "shareholderName": "NLFI",
      "shareholderIconUrl": "https://res.cloudinary.com/banq/image/upload/v1552255582/radar/icons/nlfi.png",
      "providerId": "NLFI",
      "percentage": 49.9
    }
  ],
  "stateOwned": true,
  "countryHQ": "NL",
  "countries": ["NL"],
  "compliance": [
    { 
      "regulation": "PSD2",
      "status": "inProgress"
    }
  ],
  "sandbox": {
    "status": "available",
    "sourceUrl": "https://medium.com/abn-amro-developer/psd2-sandbox-available-lets-get-started-5220d7e9418b"
  },
  "developerPortalUrl": "https://developer.abnamro.com/",
  "apiProducts": [
    {
      "label": "Account Information",
      "type": "accountInformation",
      "categories": ["accounts"],
      "description": "Retrieve details of an account such as balance transactions, balance and details.",
      "documentationUrl": "https://developer.abnamro.com/content/account-information",
      "apiReferenceUrl": "https://developer.abnamro.com/api/account-information-v1/account-information-documentation",
      "premium": false,
      "stage": "upcoming"
    },
    {
      "label": "Payment Initiation",
      "type": "paymentInitiation",
      "categories": ["payments"],
      "description": "Initiate a single payment and retrieve information on the status of the transaction.",
      "documentationUrl": "https://developer.abnamro.com/content/payment-initiation",
      "apiReferenceUrl": "https://developer.abnamro.com/api/payment-initiation-v1/payment-initiation-documentation",
      "premium": false,
      "stage": "upcoming"
    },
    {
      "label": "Tikkie Payment Request",
      "type": "other",
      "description": "Get paid faster by creating easy payment requests. Share them via any channel you want.",
      "categories": ["payments"],
      "documentationUrl": "https://developer.abnamro.com/content/tikkie-payment-request",
      "apiReferenceUrl": "https://developer.abnamro.com/api/tikkie-v1/tikkie-api-documentation",
      "premium": true,
      "stage": "live"
    },
    {
      "label": "Tikkie Fast Checkout (for Webshops & E-commerce)",
      "type": "other",
      "description": "Boost the conversion rate of your webshop by enabling customers to checkout in just a few seconds.",
      "categories": ["payments"],
      "documentationUrl": "https://developer.abnamro.com/content/tikkie-fast-checkout",
      "apiReferenceUrl": "https://developer.abnamro.com/api/tikkie-fastcheckout-v1/tikkie-fast-checkout-documentation",
      "premium": true,
      "stage": "live"
    },
    {
      "label": "Tweadle",
      "type": "other",
      "description": "Offer a responsible, clear and easy to use loan facility to your customers by allowing them to pay their purchase in monthly instalments.",
      "categories": ["loans"],
      "documentationUrl": "https://developer.abnamro.com/content/tweadle",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "privateBeta"
    },
    {
      "label": "Terminal Data",
      "type": "other",
      "description": "Receive data that has been generated by your Point Of Sale terminal during a transaction to automate your reconciliation.",
      "categories": ["payments"],
      "documentationUrl": "https://developer.abnamro.com/api/tikkie-v1/tikkie-api-documentation",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "prototype"
    },
    {
      "label": "Notification Kit",
      "type": "other",
      "description": "Receive webhook notifications for a wide range of use cases and automate banking processes when something changes on your account.",
      "categories": ["accounts"],
      "documentationUrl": "https://developer.abnamro.com/content/notification-kit",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "prototype"
    },
    {
      "label": "Check Kit",
      "type": "other",
      "description": "Validate client data for a wide range of use cases by getting a true or false response on topics like age, address and salary range.",
      "categories": ["accounts"],
      "documentationUrl": "https://developer.abnamro.com/content/check-kit",
      "apiReferenceUrl": null,
      "premium": false,
      "stage": "idea"
    }
  ],
  "apiStandards": [],
  "apiAggregators": [
    "klarna"
  ],
  "webApplication": true,
  "mobileApps": [
    {
      "operatingSystem": "ios",
      "storeUrl": "https://itunes.apple.com/nl/app/abn-amro-mobiel-bankieren/id439728011?mt=8"
    },
    {
      "operatingSystem": "android",
      "storeUrl": "https://play.google.com/store/apps/details?id=com.abnamro.nl.mobile.payments&hl=en"
    }
  ],
  "stockSymbol": "AMS:ABN",
  "investorRelationsUrl": "https://www.abnamro.com/en/investor-relations/index.html",
  "financialReports": [
    {
      "label": "Q4 2018",
      "date": "2019-02-13",
      "url": "https://www.abnamro.com/nl/images/Documents/050_Investor_Relations/Financial_Disclosures/2018/ABN_AMRO_Quarterly_Report_2018_Q4.pdf"
    }
  ],
  "twitter": "ABNAMRO",
  "crunchbase": "abn-amro-bank",
  "github": "ABNAMRO",
  "fca": "001b000000MfnaPAAR",
  "articles": [
    {
      "url": "https://medium.com/abn-amro-developer/psd2-sandbox-available-lets-get-started-5220d7e9418b",
      "date": "2019-03-05"
    }
  ]
}
